/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function send(username: string, timestamp: string, authtype: string, password: string, server: string, port: number, requireTls: boolean, from: string, to: string, replay: string, subject: string, body: string): Promise<void>
